name: Build and Deploy Kivy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yes | sdkmanager --licenses
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.19 virtualenv

      - name: Build and Deploy
        run: |
          pip install kivy
          pip3 install --user --upgrade buildozer
          buildozer -v android debug
        env:
          BUILD_TARGET: android
