name: build-and-release-android

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Install Cython
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user --upgrade Cython==0.29.24 virtualenv

    - name: Install Buildozer
      run: |
        python3 -m pip install --user --upgrade buildozer

    - name: Build APK
      run: |
        yes | sdkmanager --licenses # accept all sdk licenses
        buildozer -v android debug

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0
        release_name: Release v1.0
        body: |
          Release of FirstApp v1.0
        draft: false
        prerelease: false

    - name: Upload APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/FirstApp-1.0-debug.apk
        asset_name: FirstApp-1.0-debug.apk
        asset_content_type: application/vnd.android.package-archive
